FROM node:20 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build

# FROM node:20
# WORKDIR /app
# COPY package*.json ./
# COPY --from=builder /app/dist ./dist
# COPY --from=builder /app/node_modules ./node_modules
# COPY --from=builder /app/prisma ./prisma
# COPY --from=builder /app/generated ./generated 

# RUN apt-get update -y && apt-get install -y openssl
RUN ls -la 
EXPOSE 3000
CMD ["node", "dist/main.js"]